import type { Metadata } from "next";

import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { cn } from "@/lib/utils";

import { Ruda, Urbanist } from "next/font/google";
import Footer from "@/components/footer/footer";
import Navbar from "@/components/nav/navbar";

// title font
export const title = Ruda({
  display: "swap",
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-title",
  subsets: ["latin"],
});
// body font
export const body = Urbanist({
  variable: "--font-body",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "font-body antialiased bg-stone-100 dark:bg-zinc-800 text-stone-700 dark:text-stone-300 ",
          title.variable,
          body.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <main className="max-w-6xl mx-auto p-5 space-y-12">
            <Navbar />
            {children}
            <Footer />
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
